n1 = float(input('Digite um número: '))
n2 = float(input('Digite outro número: '))
print(f'A soma é {n1 + n2}')
print(f'A multiplicação é {n1 * n2}')
print(f'A subtração é {n1 - n2}')
print(f'A divisão é {n1 / n2}')
print(f'A divisão inteira é {n1 // n2}')
print(f'O resto da divisão é {n1 % n2}')
print(f'A exponenciação é {n1**n2}')
print(pow(n1,n2))
print(f'A raiz é {n1**(1/n2)}')

